### ISSUE TITLE
[BUG] extension with upper case letters don't work

### ISSUE THREAD

**Issue by a-tonchev** [Touffy/client-zip#11]
**Describe the bug**
When I zip file that has name with upper case letters - it won't work.

**To Reproduce**

const file=  new File( [ imageBlob ], 'something.JPG' );
const blob = await downloadZip( [ ...someotherfiles, file ] ).blob();
FileSaver.saveAs( blob, 'myFile.zip' );

The JPG  file is missing

**Expected behavior**
The jpg file should be in the zipped file  'myFile.zip' .

If I try with lower-case 'something.jpg', then it works

**Comment by Touffy** [comment]
Do you see this bug only with manually created Files ? What happens if you use a file input to load a file with an uppercase name from your filesystem ? how about an input object like this:
```javascript
{ name: 'something.JPG', input: imageBlob }
```

**Comment by a-tonchev** [comment]
@Touffy The problem was that there is a whitespace at the beginning of the file. 

So it does not depend on upper/lower case...

When I create new file with whitespace

`const file= new File( [ imageBlob ], ' something.JPG' );`

The filename is automatically fixed in the blob, but it does not appear in the zip file.

So I will close this for now

**Comment by Touffy** [comment]
I've tried with space-prefixed file names and it seems that client-zip includes them properly in the archive. Do you perhaps have a local filesystem that doesn't allow such filenames, so the bug actually occurs when unzipping ?

**Comment by a-tonchev** [comment]
@Touffy I use Windows 10, did you try with spaces at end?

**Comment by Touffy** [comment]
I did, just now. It unzips fine on my Mac. Of course macOS is unable to infer the file type from an extension with trailing spaces so it shows it as a binary executable.
