### ISSUE TITLE
[BUG] Unzipped files have no permission on Linux

### ISSUE THREAD

**Issue by joedakroub** [Touffy/client-zip#18]
**Describe the bug**
When unzipping a ZIP file created with `client-zip` (non-service worker version), the resulting zipped files have no permissions in Linux and are therefore locked. Once you change the permissions, the files work as expected.

I tried using a `File` object and an object literal to represent each file and had the same outcome.

**To Reproduce**
1. In a Linux environment, create a ZIP file using `client-zip`
2. Extract the files
3. Extracted files should have no permissions and possibly display a locked icon over them

**Expected behavior**
I expect the extracted files to have `664` permissions on Linux. This works as expected on Mac and Windows.

**Screenshots**
![image](https://user-images.githubusercontent.com/7331038/111079708-889db400-84d1-11eb-86a9-256b297c13cb.png)

**Desktop (please complete the following information):**
 - OS: Pop!_OS 20.10 (Ubuntu variant)
 - Browser: Chromium
 - Version: 89

**Comment by Touffy** [comment]
Interesting. I don't set any extra fields for permissions as I also expected the default to be sensible. Really weird that you don't get that on your OS. I'd be curious to know if any other Linux user has this issue.

What are you using to unzip the archive ? do you set a default app to open Zip files ? or does your Chromium actually unzip them on its own ?

**Comment by joedakroub** [comment]
Thank you for the reply! I am using the built-in `Extract` program in Ubuntu (which is the default for opening Zip files). So the zip I create gets downloaded in Chromium and then I open it from the Desktop; nothing unusual. 

I did some digging to see if this is a common thing with other Zip libraries on Linux, and found that it actually is a bit of an issue. Some of the libraries mention extra fields and one of them was fixed by setting permissions in the extra field. 

Here is one example: 
https://github.com/dotnet/runtime/issues/1548#issuecomment-641593908

**Comment by Touffy** [comment]
Thanks for digging. If I understand correctly, it's not even an extra field, just a few bytes in the basic file header that I thought were not important and was leaving at zero.

**Comment by joedakroub** [comment]
Yes, you are correct; looks like some extra bytes for the file header.

**Comment by Touffy** [comment]
I added the bits where I think they should be, but I don't know if it works. When extracted on my system it always has the default permissions. Could you try [this version](https://touffy.me/client-zip/permissions.js) ? And if that doesn't work, the [little-endian version](https://touffy.me/client-zip/permissions-le.js)

**Comment by joedakroub** [comment]
Absolutely! I tried both versions: the first version has the same permissions issue and the little-endian version yields an empty zip file.

**Comment by Touffy** [comment]
Empty ? that's so weird. But maybe I know why. So in that second file, I guess I was writing to the correct end of the 32-bit flags, but actually writing as big-endian. Could you try again with the new, really little-endian version ([same URL](https://touffy.me/client-zip/permissions-le.js)) ?

**Comment by joedakroub** [comment]
The new little-endian version works as expected! I tested it on a variety of files and nested directories; everything has the correct permissions now! Thank you so much for looking into this and for the terrific library. 🙌🏼 🙇🏼

**Comment by Touffy** [comment]
Thanks for your feedback. I'll publish the fix as soon as I have a moment of free time.
