### ISSUE TITLE
MacOS Date Modified is incorrect and years in the future or the past

### ISSUE THREAD

**Issue by duttonkj** [Touffy/client-zip#2]
Thanks for the great package!  It's lightning fast and super reliable.

We have installed in our app and during QC and noticed the following issue. `Date Modified` is showing some wild dates:

![image](https://user-images.githubusercontent.com/833755/79991618-83321800-8480-11ea-88ba-156279c49b2e.png)

I have attempted to set the `lastModified` property with `new Date()` but it still has issues:

![image](https://user-images.githubusercontent.com/833755/79992321-54687180-8481-11ea-8b6c-891c9014fd5f.png)

**Comment by Touffy** [comment]
Oh dear. I couldn't find proper documentation on the DOS date/time format used by ZIP (especially the byte order which I may have gotten completely wrong). I'll look into it more.

Just in case, have you checked the date on your original resources (Last-Modified header for Responses, or lastModified property on Files) ?

**Comment by duttonkj** [comment]
Yes, we are using Cloudfront to serve images and it provides a `Last-Modified` header.

**Comment by duttonkj** [comment]
Thanks for the quick fix. That works for our use case

**Comment by Touffy** [comment]
You're welcome. Thank you for using client-zip and getting me to finally dive into this issue and get it right (I think — I really hope that using the client's timezone will work for everyone).

**Comment by mfrobben** [comment]
Thank you!
