### ISSUE TITLE
[FEATURE] Unicode Path extra field

### ISSUE THREAD

**Issue by Touffy** [Touffy/client-zip#23]
Some old zip utilities do not understand UTF-8 in the basic filename field. They require the "Unicode Path Extra Field" instead.

That field could be included automatically whenever the original filename contains non-ASCII characters, while the basic field would be normalized to ASCII.

A solution along those lines was submitted in #22 . However, the cost in terms of extra code in the library and extra bytes in the generated archive was deemed too high compared to the gain (compatibility with a single outdated Zip utility identified so far). client-zip itself requires a very recent Web browser, so it's unlikely that it will run on a system that has an irremediably obsolete Zip program.

Please post in this thread if you run into the issue, and specify which Zip program is causing it.

**Comment by demidov71** [comment]
The latest Windows 11 has the same problem with its built-in ZIP shell extension.

**Comment by Touffy** [comment]
Does it break only since Windows 11 ? Is this shell extension used by default when a user downloads a file from Edge, or is it only something you use explicitly on the command-line ?

**Comment by demidov71** [comment]
I think they use the same code base for all of them since Windows 7, but I'm not sure.
It's part of the shell - WIndows Explorer shows ZIP files as virtual folders. You can enter this folder and view its content as if it's a real one. The extension also allows to extact the archive.

**Comment by Touffy** [comment]
OK. So on any Windows PC since before client-zip existed, when browsing the files generated by client-zip, users will see UTF-8 names interpreted as… a character set based on the system locale ? sounds pretty bad.

Anyway, that's what it say on [this Microsoft page about Windows 11](https://answers.microsoft.com/en-us/windows/forum/windows_10-files-winpc/windows-10-cannot-compressed-foldersfiles-that/f6e7884b-bdba-402a-8655-142f8bdf75d5).

So the UTF-8 extra field may not solve the issue in this case. It sounds like the crappy Zip library used in Windows Explorer simply doesn't support Unicode in any shape or form (have you tried creating your Zip file with, say, 7zip, and opening it with Windows Explorer ? does it work ? doe it work if you set the system local to the "wrong" language ?).

If so, the only way to make a Hebrew or Cyrillic name show up correctly would be to encode it with the user's system encoding (assuming that encoding is appropriate) in the basic filename field.

It's doable, mind you. But the TextEncoder API in browsers typically doesn't support anything other than UTF-8, which means I'd have to bundle Windows encodings into client-zip, just to work around that Windows issue. Which, frankly, does not seem acceptable.

**Comment by demidov71** [comment]
No, please, don't make anything as stupid as system encoding. Everything should stay UTF-8. And if "extra field" makes code ugly, leave it. We all use 7zip anyway.
However, when making zip with 7zip and multiple languages, namely, Hebrew and Russian, together, so that system code page would not help, I receive an archive, that is underdtood by Windows 11 well.

**Comment by Touffy** [comment]
The extra field in itself doesn't make the code ugly, just a bit longer, and it's a waste for most users. There is also the question of how do you downgrade the filename to ASCII (for the basic filename field) when it's not Latin to begin with. That part could be ugly. Of course it would be better for everyone if Microsoft just patched their implementation.

Thanks for testing. Can you send me an example archive (ideally with just one or two empty or very small files) that works in Explorer with mixed Hebrew/Russian ?

**Comment by demidov71** [comment]
This archive is made by 7zip. Works well in Windows 11 Explorer.

**Comment by Touffy** [comment]
I think you tried replying to GitHub and attaching a file. Doesn't work that way. You can easily find my personal email on my profile.

**Comment by Touffy** [comment]
Hopefully the addition of the EFS bit in the header flags (#42) has fixed the issues with Windows Explorer without having to implement the Unicode extra field.
