### ISSUE TITLE
Add canvas image to zip

### ISSUE THREAD

**Issue by rashid-naico** [Touffy/client-zip#25]
I have canvas with image, converted to dataURL()

 const img = document.getElementById("canvas_output").toDataURL();

const blob = await downloadZip([  img ]).blob();

this gives me error

**Comment by Touffy** [comment]
I hope so. A string is *not* a valid input type for client-zip. You can include the string as the "input" property of a valid input object, or (better) get a Blob or ArrayBuffer from the canvas instead of a data URL, that would be more efficient.

**Comment by rashid-naico** [comment]
It worked @Touffy 
```
const img = document.getElementById("canvas_output").toDataURL();
// added fetch call
const file = await fetch(img );
const blob = await downloadZip([ file ]).blob();
```

**Comment by Touffy** [comment]
Yeah, it worked but it's a bit convoluted. A Blob is *definitely* the way to go here. Use the [canvas.toBlob() method](https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/toBlob) to get the data directly without going through a long URL. And be careful with the filename you use. By default, `toBlob()` and `toDataURL()` will produce a PNG, not a JPEG (but you can configure that).

**Comment by Touffy** [comment]
Just to be clear, this is your code, modified to use `toBlob()` and configured to actually output JPEG instead of PNG (so the filename is consistent):
```js
const filedata = document.getElementById("canvas_output").toBlob('image/jpeg');
const file={ name: 'myfile.jpg', input: filedata }
const blob = await downloadZip([ file ]).blob();
```
