### ISSUE TITLE
what is the performance benchmark?

### ISSUE THREAD

**Issue by tapanjo92** [Touffy/client-zip#27]
Hi,

thinking of using client-zip instead jszip. But can it zip about 20GB files on a browser with low CPU/memory usage?

Thank You

**Comment by ricky11** [comment]
i am currently using client-zip using service workers (as described in the doc) to zip over 4gb of multiple files. have not tried more than that but  should work.

**Comment by Touffy** [comment]
Like Ricky says. It will still be a little slow if you have a slow CPU, but certainly not as slow as JSZip ! Did you actually have the patience to let JSZip process 20GB ? that must have taken hours.

I would appreciate your feedback once you've worked it out with the ServiceWorker.

**Comment by tapanjo92** [comment]
Even zipping approx 2GB was a nightmare on JSZip. We will try with client-zip now and let you know :)

**Comment by ricky11** [comment]
Here is a production link for 21gb (2 files) using client-zip

https://sinosend.com/d/OFC84oC

if you have the patience, and a good network connection, should work, let me know otherwise.
(does not work in older browsers and safari)

**Comment by tapanjo92** [comment]
thank you for that @ricky11 
Whats the issue with safari btw?

**Comment by Touffy** [comment]
When a download link is supposed to be intercepted by the Service Worker, in Safari it isn't and goes straight to the network. There seems to be a workaround using an iframe, I haven't tried it yet but anyway, it sucks.

**Comment by Touffy** [comment]
(https://bugs.webkit.org/show_bug.cgi?id=202142)

**Comment by ricky11** [comment]
try this in both chrome and safari 
if you come up with the solution, please do let me know , even a crappy workaround.

https://serviceworke.rs/local-download_demo.html

**Comment by Touffy** [comment]
Good news ! I've been following that WebKit bug and it's finally being fixed ! Hopefully by the time they release Safari 16.

**Comment by ricky11** [comment]
Wow wow .. great.. now need to test for safari 16 before allowing the service worker.
