### ISSUE TITLE
[BUG] Extracting duplicate files

### ISSUE THREAD

**Issue by xsurge83** [Touffy/client-zip#32]
**Describe the bug**
We have a Windows user that is reporting duplicate files after unzipping the folder. Does `client-zip` tested on Windows OS? 

**To Reproduce**
1. Concat multiple `File` using `await downloadZip([file]).blob()`
2. Unzip file on Windows machine. 

Unzipping the same files works on Mac OS. 

**Expected behavior**
Should unzip with one file or number of files provided to `downloadZip`

**Desktop (please complete the following information):**
 - OS: Windows 
 - Browser: Chrome
 - Version:

**Comment by Touffy** [comment]
I haven't tested it on Windows, no. Can you post the actual Zip file downloaded by your user or reproduce the issue ? it's possible that they included the same file twice in the archive if your system allows it (client-zip currently accepts multiple entries with duplicate filenames, which could be fixed easily if that's the source of your bug).

**Comment by xsurge83** [comment]
I can't share the zip file. We download the file on the client side and call `downloadZip`. Here is the snippet: 

```
downloadZip([new File(respons.body as Blob, filePath)]);
```

**Comment by Touffy** [comment]
Out of curiosity, why are you not using the Response itself as input for downloadZip ? or a custom object with the Response as `input` and a `filename` ?

Anyway, I really don't see why that code would cause client-zip to duplicate the entry. I would need a reproducible case to debug it. Are you sure the user isn't just opening the zip file twice ?

**Comment by Touffy** [comment]
Any news ?

**Comment by Touffy** [comment]
I'm closing this until someone sends me enough data to reproduce the bug.
