### ISSUE TITLE
[BUG] non-english file names

### ISSUE THREAD

**Issue by demidov71** [Touffy/client-zip#39]
Files with non-english names, e.g. hebrew or russian, are packed into archive so, that Windows ZIP shell extension sees them as gibberish.
On the other hand, 7zip sees them correctly.

**Comment by Touffy** [comment]
Looks like the same issue as #23 . Please use that and add some details (like the version of Windows and the shell extension).

**Comment by demidov71** [comment]
Not so outdated - Windows 11 Enterprise, ver. 21H2.
