### ISSUE TITLE
[FEATURE] Store paths as well as names

### ISSUE THREAD

**Issue by magnus-anderholm-sweco-se** [Touffy/client-zip#41]
From what I understand (please correct me if I'm wrong) it is currently only possible for client-zip to generate a "flat" zip file. I.e. no folder paths in the zip file. Would it be very difficult to add this?

**Why is your feature relevant to client-zip?**
There are definitely a use cases where this would be useful. On top of my head.
* Avoids having to mangle the filename itself if there are duplicate filenames in the files/requests to be stored in the zip. (Just use different folders)
* Keep folder structure if user needs to download files from a system that actually stores files in folders (plenty). Duplicate filenames are often not that rare in those cases.

**Describe the solution you'd like**
Make it possible to not only specify name for a entry in the zip package but also folder path (relative is probably enough).

**Comment by Touffy** [comment]
Please see #6

**Comment by magnus-anderholm-sweco-se** [comment]
Doh! I should have seen that. My bad. Thank you for the prompt response
