### ISSUE TITLE
[BUG] Breaks react-native build with obtuse error

### ISSUE THREAD

**Issue by pfych** [Touffy/client-zip#45]
**Describe the bug**
When using `client-zip` in a shared context, `react-native` fails to build.

We have both a web & mobile app that use a shared "core" folder.
```
myApp/
├─ clients/
│  ├─ core/
│  │  ├─ sharedFunction.ts
│  │  ├─ package.json
│  ├─ web-app/
│  │  ├─ app.tsx
│  │  ├─ package.json
│  ├─ react-native-app/
│  │  ├─ app.tsx
│  │  ├─ package.json
```
We use `client-zip` inside `core` for a util that is shared between web & mobile. This however breaks the mobile build with the following error:

```
Compiling JS failed: 6000907:22:invalid numeric literal Buffer size 3141939 starts with 766172205f5f42554e444c455f535441
```

Looking online nothing appears for "`Compiling JS failed invalid numeric literal Buffer size starts with`" other than this [single stack-overflow question](https://stackoverflow.com/questions/72104175/compiling-js-failed-react-native-expected-buffer-size) which involves handling promises incorrectly.

We fixed this issue by moving the function declaration to `web-app` & not allowing the feature to be used natively on mobile.

The function looked like this:
```ts
// ... Truncated
const zipStreamAsBlob = await downloadZip(
  blobs
    .filter((blob) => blob.file)
    .map((blob, i) => ({
      input: blob.file!,
      name: `${files[i].name}${files[i].uri.slice(
        files[i].uri.lastIndexOf('.'),
      )}`,
    })),
).blob();
// ... Truncated
```

Our work-around is good for now, we didn't exactly need the feature in mobile however there was *nothing* online about this issue so I believe its still worth posting.

**Expected behavior**
React native project should build

**Screenshots**
![imgur](https://imgur.com/8Da394z.png)

**Desktop:**
 - OS: macOS Monterey (12.4)

**Smartphone:**
 - Device: iPhone 13 Pro
 - OS: iOS 15.5

**Comment by Touffy** [comment]
Hi Noah. I'm not sure what to do with this issue. I suppose it can just stay here in case other people try to do the same thing you did. I have no idea what the error really means. It seems to indicate a flawed assumption in some compiler. Just in case, have you tried using client-zip 1.x (which doesn't have BigInts) ?
