### ISSUE TITLE
Can I use this in my Android App (Ionic framework) ? 

### ISSUE THREAD

**Issue by pratiksan45** [Touffy/client-zip#5]

**Comment by Touffy** [comment]
Yes, of course. It will run in any modern browser or browser-like environment including Electron/Ionic/etc.

However, Cordova can zip files using native capabilities rather. A quick search yielded [this ZIP plug-in](https://www.npmjs.com/package/cordova-zip-plugin). client-zip is quite fast for a JavaScript implementation, but it is still about 70 times slower than native, so I would recommend using the plug-in. Also, Cordova will let you manipulate the filesystem directly without the drastic restrictions of standard browser APIs.

**Comment by Touffy** [comment]
Does that answer your question, @pratiksan45 ?

**Comment by pratiksan45** [comment]
Hi, 
I have tried to use your plugin in my mobile app. But the zip file  I am getting is of the same size. The file is not compressed, I have tried the same with all size of files from 20kb to mb.  ??

**Comment by Touffy** [comment]
Your observations are correct. As the README clearly states, client-zip does not perform compression. It was not a necessary or even desirable feature to solve the problem that prompted the creation of this library.

It is in the roadmap but not prioritized at the moment. If you need compression, please explain your use case, and which algorithm you would like to have.

**Comment by pratiksan45** [comment]
Ok. Got that. 
One small Question. 
Can I zip multiple files using this??

**Comment by Touffy** [comment]
Yes! Zipping multiple files was the whole point. You can pass an array of files if you've got all your inputs ready, or pass a generator if you'd rather make the files available one by one.

**Comment by pratiksan45** [comment]
Ok @Touffy . Thanks for the help.
