### ISSUE TITLE
[BUG] downloadZip creating corrupted zips in demo

### ISSUE THREAD

**Issue by ahmedmohiduet** [Touffy/client-zip#53]
I am running this simple script from demo and its creating corrupted zip file:

```
function test() {
  // an ArrayBuffer
  const hi = new TextEncoder().encode("hello world!")
  // just a string
  const bye = "goodbye."

  const blob = downloadZip([
    { name: "hello.txt", lastModified: new Date(), input: hi },
    { name: "goodbye.txt", lastModified: new Date(), input: bye }
  ]).blob()

    const link = document.createElement("a")

    var binaryData = [];
    binaryData.push(blob);

    link.href = URL.createObjectURL(new Blob(binaryData, {type: "application/zip"}))
    link.download = "hello+goodbye.zip"
    link.click()
}

document.getElementsByTagName("button")[0].onclick = test
```

While I am opening `hello+goodbye.zip` with `vim`, I can only find a text:
`[object Promise]
`
No file list in zip file and it also can not be opended in `nautilus` either.

**Comment by Touffy** [comment]
This is not the demo script. Did you ask ChatGPT to write this mash-up of blob usage ?

**Comment by Touffy** [comment]
If you genuinely think your code should work — after reading it a couple more times —, feel free to continue the conversation (though StackOverflow would be more suitable for this kind of problem). But I'm closing the issue as it has absolutely nothing to do with client-zip.
