### ISSUE TITLE
generated xlsx file but office show error when open it

### ISSUE THREAD

**Issue by coader** [Touffy/client-zip#61]
[test.xlsx](https://github.com/Touffy/client-zip/files/11413997/test.xlsx)
[test2.xlsx](https://github.com/Touffy/client-zip/files/11413998/test2.xlsx)

the first xlsx is generated by client-zip
the second is unzip by 7zip and then zip again with store only option

office can open the second correctly but show error for the 1st

**Comment by Touffy** [comment]
This may be the same thing as #59 . Can you try with [client-zip v1](https://github.com/Touffy/client-zip/releases/tag/v1.5.1) and see if you still can't open the file ?

**Comment by Touffy** [comment]
I tried downloading your test files, but I end up with an empty file for the first, and just 9 bytes for the second. Might be an issue with GitHub hosting those files.

I'm going to close this issue because it's very, very likely to be a duplicate of #59. Reopen if not.
