### ISSUE TITLE
[BUG] You may need an appropriate loader to handle this file type

### ISSUE THREAD

**Issue by jawainc** [Touffy/client-zip#70]
**Describe the bug**
In my Nuxt project I'm using in component like and its giving the error
`You may need an appropriate loader to handle this file type`

**To Reproduce**
add import in vue component
`import { downloadZip } from "client-zip";`

any solution to this error

**Comment by Touffy** [comment]
Thanks, that settles it. Your Nuxt toolchain is set up to read "old" JavaScript and it can't parse the [optional chaining operator `?.`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining) which is an ES2020 addition. It would also crash on nullish coalescing (`??`) and the few bigint litterals further down, and unlike the first two, you cannot easily transpile BigInt code to a lower ES version.

You could try to upgrade the transpilation target for Nuxt to ES2020 and hope there isn't an intermadiate step that you can't touch with your config files.

Or, if you never create archives larger than 4 GB, just use client-zip version 1.x (which doesn't need BigInts and is already transpiled to ES2018).

**Comment by jawainc** [comment]
Thanks downgrading to 1.x works
