### ISSUE TITLE
[BUG] Zipped file is empty

### ISSUE THREAD

**Issue by mrtnvgr** [Touffy/client-zip#79]
**Describe the bug**

Hi! For some reason my zipped files are always empty.

**To Reproduce**

<details>
<summary>Code snippet</summary>

```js

import { downloadZip } from "https://cdn.jsdelivr.net/npm/client-zip/index.js";

async function initRecorder() {
	window._recordings = [];
	window._chunks = [];

	try {
		let audio_stream = await navigator.mediaDevices.getUserMedia({ audio: true });
		window._recorder = new MediaRecorder(audio_stream);
	} catch (e) {
		console.log(e);
		alert("Failed to get microphone permissions\nYour answers won't be recorded");
		return;
	}

	_recorder.ondataavailable = (e) => {
		_chunks.push(e.data);
	};

	_recorder.onstop = (e) => {
		let blob = new Blob(_chunks);

		let task_directory = `Task ${current_task}`;

		let count = 0;
		for (let recording of _recordings) {
			if (recording.name.includes(task_directory)) {
				count++;
			}
		}

		_recordings.push({
			name: `${task_directory}/${count+1}.ogg`,
			input: blob,
		})

		_chunks = [];
	};
}

async function showDownloadPage() {
	console.log(_recordings);
	let blob = await downloadZip(_recordings).blob();
	console.log(blob);
        ...
}

```

</details>

**Expected behavior**

**Screenshots**
![20231203_19h25m50s_grim](https://github.com/Touffy/client-zip/assets/48406064/53e8aa97-d0e0-4530-bbd0-71e05b859b6b)

**Desktop:**
 - OS: Linux
 - Browser: firefox
 - Version: 119.0.1

**Additional context**

**Comment by mrtnvgr** [comment]
Oh, thats interesting. It seems that multiple files zip just fine 🤔 

![20231203_20h52m20s_grim](https://github.com/Touffy/client-zip/assets/48406064/44dbb166-9a08-4f70-bfe2-22b172c54fc4)

**Comment by Touffy** [comment]
So… does the empty archive occur only when you add a single file ?

I can't spot anything wrong with your code, anyway.

**Comment by mrtnvgr** [comment]
When debugging I found out that `_recordings.length` appears to be incorrect for some reason...

```js
async function showDownloadPage() {
	console.log(_recordings);

	// TODO: https://github.com/Touffy/client-zip/issues/79
	if (_recordings.length == 1) {
		_recordings.push({ name: "ignore_me", input: "nothing" });
		console.log(_recordings);
	} else {
		console.warn(_recordings.length);
	}

	let blob = await downloadZip(_recordings).blob();
	console.log(blob);
        ...
```

![20231206_20h51m12s_grim](https://github.com/Touffy/client-zip/assets/48406064/6477f7ea-1bed-41ee-8379-745be2434a63)

**Comment by mrtnvgr** [comment]
@Touffy I'm not good to javascript, would you mind helping me please?

**Comment by Touffy** [comment]
The issue seems to be with the *_recordings* array. Because it has apparently a length of 0, even though it contains an item. There may be some corruption of `Array.prototype` in your surrounding code, or something weird when * _recordings* is created. I cannot understand the issue without seeing more code.

One way to get that strange behaviour would be to set `_recordings.length` to zero explicitly… perhaps somewhere in a condition you wrote `_recordings.length = 0` instead of `_recordings.length == 0` ?

**Comment by mrtnvgr** [comment]
> The issue seems to be with the *_recordings* array. Because it has apparently a length of 0, even though it contains an item. There may be some corruption of `Array.prototype` in your surrounding code, or something weird when * _recordings* is created. I cannot understand the issue without seeing more code.
> 
> One way to get that strange behaviour would be to set `_recordings.length` to zero explicitly… perhaps somewhere in a condition you wrote `_recordings.length = 0` instead of `_recordings.length == 0` ? (though that *should* also remove the item)

Thanks for your help, [here](https://github.com/mrtnvgr/eggs/blob/master/www/main.js) is the full file

**Comment by Touffy** [comment]
Ah ! I think I found it. You are calling `showDownloadPage()` too soon. `_recordings` is empty when the archive is created (set a breakpoint at the call to `downloadZip` — after the `await` — and you will see).

But `console.log` is somewhat asynchronous when you give it an object, and shows the contents of `_recordings` at the time when the browser actually renders the message, not the instant when you called `console.log`. In that tiny amount of time, `_recordings` has been updated, so you see an array with one item in your console.

**Comment by Touffy** [comment]
<img width="1509" alt="breakpoint" src="https://github.com/Touffy/client-zip/assets/665732/4b150f52-a457-4cf1-b23e-fcc5099c527d">

The `_recorder.onstop` event is triggered immediately **after** that, and that's where you push the recording to the array.

**Comment by mrtnvgr** [comment]
Oh, thank you so much! :heart: 

What is the best way to fix this? To wait until the event hooks are finished their tasks? How can I do it?

**Comment by mrtnvgr** [comment]
Maybe a custom state, something like `processing`?

**Comment by mrtnvgr** [comment]
[All fixed now](https://github.com/mrtnvgr/eggs/commit/f7198ffde81ce95b7328166c9da67f87d8c7c7ff), thanks again!
