### ISSUE TITLE
fetch throws a " Error: The file must have a name. "

### ISSUE THREAD

**Issue by kjo-sdds** [Touffy/client-zip#84]
https://github.com/Touffy/client-zip/blob/3937d6be5db9c01e5809fc30097bbf8cfa94ee1e/demo/index.html#L30

Even the example seems to be not working for me ... (I spent so much time thinking I had done something wrong ... not finding the difference between mine and the example ...)

I believe it used to work back in beginning og 2023 if that can help ...

**Comment by davidjunger-oa** [comment]
You're right. The inputs can't be promises, I don't remember if that could work before but I don't see how. The example in the README correctly `await`s the code.

**Comment by Touffy** [comment]
You're right. The inputs can't be promises, I don't remember if that could work before but I don't see how. The example in the README correctly awaits the code.
