### ISSUE TITLE
[Helpwanted] worker.js with dl-stream

### ISSUE THREAD

**Issue by ricky11** [Touffy/client-zip#88]
https://github.com/Touffy/client-zip/blob/master/demo/worker.js

I am using the above worker script and passing in the intercepted fetch urls.  The zip genertes and all files are intact, however I would like to maitain folder structure, hence I also have an array of the filePaths that include folders names such as 
['\fodlerA\file1.txt','\folderA\file2.txt,'\folderB\file1.txt'] etc.

I guess i would need to adjust this line in the code to add in the name property but need some guidance on how to do that

      .then(data => downloadZip(new DownloadStream(data.getAll('url'))))

is it downloadZip({name: [Array of filePaths], newDownloadStream(data.getAll('url)))

I've seen https://github.com/Touffy/client-zip/issues/6 but still cant figure it out.

Would love a demo file to show us how this would work.   Thanks.

**Comment by Touffy** [comment]
1. As stated in the README, all file paths must use the forward slash "/" as a path delimiter. It's encoded that way in the Zip format — regardless of the origin platform — and client-zip does not try to convert from Windows paths.
2. Sorry, you cannot pass an array of filenames to downloadZip. Each file or folder has to be its own entry with its own filename.

As you noticed, client-zip will remove the path in the URL when extracting the filename from a Response. You'll have to map the responses from the DownloadStream to objects with an explicit filename to override that behaviour.

If all you need is to preserve the full pathname from each Response's URL, then this would do it :

```js
// define this anywhere
async function *renameFromURL(responses) {
  for await (const response of responses)
    // this is where you pick a name for each file
    yield {input: response, name: new URL(response.url).pathname}
}

// then, in the fetch listener…
  event.respondWith(event.request.formData()
    // the only difference is wrapping the stream with renameFromURL() :
    .then(data => downloadZip(renameFromURL(new DownloadStream(data.getAll('url')))))
    .catch(err => new Response(err.message, { status: 500 }))
  )
```

**Comment by ricky11** [comment]
Thanks, that worked. 

Alternatively i was thinking, the data.getAll('url') already contains a property named `webkitRelativePath` which contains the name with forward slashes for folder names, or null if a file.   Can clientZip detect if webkitRelativePath exists and use that as the name value, and if it doesn't exist use the File name as normal?

**Comment by Touffy** [comment]
I am confused. You said you were using my demo worker script, which fetches file contents over HTTP by using the URLs from the intercepted formData. But `webkitRelativePath` only exists for `<input type=file>` elements with a webkit-specific attribute, not for `<input type=url>`. May I assume that you are in fact using file inputs in your user interface, and that you have already modified my script to some extent ?

If you are indeed using file inputs, there will be no URLs and no need to fetch data with a DownloadStream, and yes, you would instead use File properties (including `webkitRelativePath` in Webkit browsers) to make a filename, and the File itself as the input. My example above was based on the assumption that you were still using URL inputs.

**Comment by ricky11** [comment]
Sorry, to clarify I am using a form to collect uploaded files, saving them to an s3 bucket, and i am using the webkitrelativePath for storing the keys in the users folders.

your right webkitrelativepath has nothing to do when downloading the object -- here i am only using form data on submit with your worker script to intercept the fetch call on the signed url. Strangely in my last post i was thinking the url is a File object but its just a string url, and obviously doe not have any metadata. 

so to clarify i am using signed urls.





Yes, I am using perhaps an older version of client-zip, and I am using a form submit and intercepting the fetch with a worker.  In my template, i am using :  
<input v-for="url in payload.fileObjects" :key="url.fileName" type="hidden" name="url"
                      :value="url.url" />
                 This adds a signed url to formdata.

**Comment by Touffy** [comment]
If you have a way to associate the signed urls (or some HTTP header in the S3 response) with metadata you saved when the file was uploaded, that would work. But if the URL already contains the correct pathname, it's easier to just use that in your case.

**Comment by ricky11** [comment]
Storing the parent folder hierarchy in the headers is a good idea, would i still need to a generator function in your example to add the name: from the header?

The URL does contain the correct path name, but its rather cumbersome to extract

https://s3......../uuid/requests/slug/<this is where the real filename starts including folders>/file.txt

so i would need to regex extract from the .pathname after a x number of trailing slashes the correct name, which could be prone to errors, it would probably now be better to store them in headers.

thanks for your input.

**Comment by Touffy** [comment]
Yes, no matter how you compute the filename, you need the async generator to set that `name` property on each entry.

That would be true even if your formData contained Files with a `webkitRelativePath`, since client-zip doesn't look at that property on its own.

**Comment by ricky11** [comment]
I decided to go with added meta data to the headers, it works great and I can access it in the response as 

const dirPath = response.headers.get('x-oss-meta-dirpath');

The zip nested folders are created and organized well, there is only an issue if a filename is saved with a trailing slash which is allows by windows and mac os, however this will rarley happen.

However an issue i noticed now is if there are no folders, just flat files, the zip will still put them in a folder, and i cant figure out why.

This is what i have so far, that works, just that urls that dont have any metadata indictes they are not to be stored in a folder and treated as normal, but when i unzip i can see a folder of the same name as the file itself.

> worker.js

`importScripts('./client-zip-worker.js', './dl-stream-worker.js')

async function* renameFromURL(responses) {
  for await (const response of responses) {

    const dirPath = response.headers.get('x-oss-meta-dirpath');

    console.log('dir paths', dirPath)
    if (dirPath) {
      console.log(true)
// this means that there webkitRelativePath was present when the file was uploaded to oss and the metadata shows the correct folders
      yield { input: response, name: dirPath }
    } else {
// this means that this was uploaded as a file, with a empty x-oss-meta-dirpath header
      console.log(false)
      yield { input: response }
    }

  }

}
self.addEventListener("fetch", (event) => {
  const url = new URL(event.request.url)
  console.log('v8')
  self.skipWaiting();
  // This will intercept all request with a URL starting in /downloadZip/ ;
  // you should use a meaningful URL for each download, for example /downloadZip/invoices.zip
  const [, name] = url.pathname.match(/\/downloadZip\/(.+)/i) || [,]
  if (url.origin === self.origin && name)
    event.respondWith(event.request.formData()
      .then(data => {
        const urls = data.getAll('url');

        return downloadZip(renameFromURL(new DownloadStream(urls)))
      })
      .catch(err => new Response(err.message, { status: 500 }))
    )
})`

**Comment by Touffy** [comment]
Most Zip programs automatically create a folder around multiple "root" files (typically with the name of the archive). It is a common but unspecified behaviour and the Zip format itself has no control over it. The best you can do is name the archive appropriately for users whose Zip program does that. You, of course, can use a program that extracts without creating the root folder, or that can be configured that way.

Technically, it may be possible to store files with a trailing slash, but the output would be unreliable (depending on filesystem and the Zip program used to open the archive). Unless there is an actual use case, I'd rather keep client-zip's policy of removing trailing slashes from filenames.
