### ISSUE TITLE
[BUG] Strange CORS error when downloading multiple files

### ISSUE THREAD

**Issue by ricky11** [Touffy/client-zip#89]
**Describe the bug**
CORS error when using client-zip to download multiple files in the service worker. But when downloading them individually using normal anchror tag, the download works.  Souce urls are s3 object urls with sts tokens, they are behind a CDN.

**Expected behavior**
Files to be streamed and zip download

**Screenshots**
<img width="467" alt="image" src="https://github.com/user-attachments/assets/0fb8cd12-bcd1-48d5-a664-13f62d1fdd57">
<img width="1309" alt="image" src="https://github.com/user-attachments/assets/d03c46c2-7910-4828-a334-f8d47c893112">

This is quite possibly an issue on my  side after adding a CDN layer on top of S3 and may have to do with retaining the url params such as filename and content disposition (as directly from s3 client-zip worked perfectly), however I have verified that the url params are intact as the files can be downloaded individually normally.  

Strangely it fails only with certain files, and I am yet to determine why.  I wanted to ask here if there was a known issue with service workers and the urls from a  CDN using a caching policy that may generate a cors ERROR.  The cdn is configured to allow all origins as files can be downloaded from the same url individually.

Below is my worker.js file

`importScripts('./client-zip-worker.js', './dl-stream-worker.js')

async function* renameFromURL(responses) {
  for await (const response of responses) {

    const dirPath = response.headers.get('x-oss-meta-dirpath');

    // console.log('dir paths', dirPath)
    if (dirPath) {
      // console.log(true)
      yield { input: response, name: dirPath }
    } else {
      // console.log(false)
      yield response
    }

  }

}
self.addEventListener("fetch", (event) => {
  const url = new URL(event.request.url)
  console.log('v11')
  // self.skipWaiting();
  // This will intercept all request with a URL starting in /downloadZip/ ;
  // you should use a meaningful URL for each download, for example /downloadZip/invoices.zip
  const [, name] = url.pathname.match(/\/downloadZip\/(.+)/i) || [,]
  if (url.origin === self.origin && name) {
    console.log('inside v11')
    event.respondWith(event.request.formData()
      .then(data => {
        const urls = data.getAll('url');
        // return downloadZip(new DownloadStream(urls))

        return downloadZip(renameFromURL(new DownloadStream(urls)))
      })
      .catch(err => new Response(err.message, { status: 500 }))
    ) 
  }
})`

**Comment by Touffy** [comment]
As you can see in your own screenshot, the `fetch` originates in dl-stream, not client-zip. client-zip never initiates any request, it just consumes Responses that you obtain for it.

What's happening is that your CDN does not set [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) headers on the responses. That would not block a direct download with an `<a>` tag, but it does prevent JavaScript from fetching the resource (or rather, it prevents JavaScript from accessing the response ; the browser does perform the request, and then throws the error after noticing the absence of CORS headers).

Your code looks fine. Anyway, there isn't anything you can do to fix this client-side. It's entirely up to the server.
